# Generated by Django 5.0.14 on 2026-07-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra / Reposição)'), ('SAIDA_VENDA', 'Saída Automática (Venda)'), ('SAIDA_PERDA', 'Saída por Perda / Descarte'), ('AJUSTE', 'Ajuste de Inventário')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data / Hora')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações / Justificativa')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
