# Generated by Django 5.0.14 on 2026-07-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo Unitário da Compra (R$)'),
        ),
    ]
