# Generated by Django 5.0.14 on 2026-09-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque_valor_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Compra / Reposição)'), ('ABERTURA', 'Carga Inicial / Abertura'), ('SAIDA_VENDA', 'Saída Automática (Venda)'), ('SAIDA_PERDA', 'Saída por Perda / Descarte'), ('SAIDA_AUTOCONSUMO', 'Saída por Autoconsumo'), ('AJUSTE', 'Ajuste de Inventário')], max_length=20, verbose_name='Tipo de Movimentação'),
        ),
    ]
