# Generated by Django 5.0.14 on 2026-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_movimentacaoestoque_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade'),
        ),
    ]
