# Generated by Django 5.0.14 on 2026-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_movimentacaoestoque_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_medio_antes',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo médio antes desta entrada'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='grupo_compra',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Grupo da compra'),
        ),
    ]
