# Generated by Django 5.0.14 on 2026-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição da Despesa')),
                ('tipo', models.CharField(choices=[('FIXO', 'Custo Fixo'), ('VARIAVEL', 'Custo Variável')], default='FIXO', max_length=10, verbose_name='Tipo de Custo')),
                ('categoria', models.CharField(choices=[('ENERGIA', 'Energia'), ('AGUA_LUZ', 'Água / Luz'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('AUTOCONSUMO', 'Auto consumo de lanches'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_pagamento', models.DateField(verbose_name='Data de Vencimento/Pagamento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Despesa / Custo',
                'verbose_name_plural': 'Despesas / Custos',
                'ordering': ['-data_pagamento', 'descricao'],
            },
        ),
    ]
