# Generated by Django 5.2.13 on 2026-08-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição da Despesa')),
                ('categoria', models.CharField(choices=[('ENERGIA', 'Energia'), ('AGUA_LUZ', 'Água / Luz'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('AUTOCONSUMO', 'Auto consumo de lanches'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia Padrão de Vencimento')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base Previsto (R$)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa (Gerar futuras?)')),
            ],
            options={
                'verbose_name': 'Despesa Fixa (Molde)',
                'verbose_name_plural': 'Despesas Fixas (Moldes)',
            },
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data_vencimento', 'descricao'], 'verbose_name': 'Despesa / Custo', 'verbose_name_plural': 'Despesas / Custos'},
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('PREVISTO', 'Previsto'), ('PAGO', 'Pago')], default='PREVISTO', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento (Real)'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='despesa_matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_geradas', to='relatorios.despesarecorrente', verbose_name='Molde Gerador'),
        ),
    ]
