# Generated by Django 5.2.13 on 2026-08-10 01:02

from django.db import migrations


def migrate_old_despesas(apps, schema_editor):
    Despesa = apps.get_model('relatorios', 'Despesa')
    # All existing despesas before this feature are considered paid.
    # Set data_vencimento = data_pagamento, and status = 'PAGO'
    for despesa in Despesa.objects.all():
        if despesa.data_pagamento and not despesa.data_vencimento:
            despesa.data_vencimento = despesa.data_pagamento
        despesa.status = 'PAGO'
        despesa.save()

class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_despesarecorrente_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_old_despesas),
    ]
