# Generated by Django 5.2.13 on 2026-08-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_auto_20260809_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
    ]
