# Generated by Django 5.2.13 on 2026-08-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_alter_despesa_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('FORNECEDORES', 'Fornecedores / Insumos'), ('ENERGIA', 'Energia'), ('AGUA_LUZ', 'Água / Luz'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('AUTOCONSUMO', 'Auto consumo de lanches'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesarecorrente',
            name='categoria',
            field=models.CharField(choices=[('FORNECEDORES', 'Fornecedores / Insumos'), ('ENERGIA', 'Energia'), ('AGUA_LUZ', 'Água / Luz'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('AUTOCONSUMO', 'Auto consumo de lanches'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
    ]
