# Generated by Django 5.0.14 on 2026-09-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0005_alter_despesa_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_referencia',
            field=models.DateField(blank=True, help_text='Dia ao qual a despesa automática se refere (fechamento / entrada de estoque).', null=True, verbose_name='Dia de referência'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Lançamento manual'), ('RECORRENTE', 'Gerada por molde fixo'), ('ESTOQUE', 'Entrada de estoque'), ('FECHAMENTO', 'Fechamento diário')], default='MANUAL', max_length=12, verbose_name='Origem do Lançamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('FORNECEDORES', 'Fornecedores / Insumos'), ('TAXA_PLATAFORMA', 'Taxa de Plataforma (iFood / UaiRango)'), ('TAXA_MAQUININHA', 'Taxa de Maquininha'), ('ENTREGA', 'Entregadores / Motoboy'), ('ENERGIA', 'Energia'), ('AGUA_LUZ', 'Água / Luz'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos (MEI / DAS)'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('VEICULO', 'Veículo / Moto (combustível, manutenção)'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('RETIRADA_SOCIOS', 'Retirada dos Sócios'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesarecorrente',
            name='categoria',
            field=models.CharField(choices=[('FORNECEDORES', 'Fornecedores / Insumos'), ('TAXA_PLATAFORMA', 'Taxa de Plataforma (iFood / UaiRango)'), ('TAXA_MAQUININHA', 'Taxa de Maquininha'), ('ENTREGA', 'Entregadores / Motoboy'), ('ENERGIA', 'Energia'), ('AGUA_LUZ', 'Água / Luz'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos (MEI / DAS)'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('VEICULO', 'Veículo / Moto (combustível, manutenção)'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('RETIRADA_SOCIOS', 'Retirada dos Sócios'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
    ]
