# Generated by Django 5.0.14 on 2026-09-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_despesa_data_referencia_despesa_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='credor',
            field=models.CharField(blank=True, default='', help_text="Quem vai receber (ex: 'Enel', 'João Refrigeração', 'Contador Silva').", max_length=120, verbose_name='Fornecedor / Credor'),
        ),
        migrations.AddField(
            model_name='despesarecorrente',
            name='credor',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Fornecedor / Credor'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('FORNECEDORES', 'Fornecedores / Insumos'), ('TAXA_PLATAFORMA', 'Taxa de Plataforma (iFood / UaiRango)'), ('TAXA_MAQUININHA', 'Taxa de Maquininha'), ('ENTREGA', 'Entregadores / Motoboy'), ('ENERGIA', 'Energia Elétrica (luz)'), ('AGUA_LUZ', 'Água / Esgoto'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos (MEI / DAS)'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('VEICULO', 'Veículo / Moto (combustível, manutenção)'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('RETIRADA_SOCIOS', 'Retirada dos Sócios'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento / Previsão de Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesarecorrente',
            name='categoria',
            field=models.CharField(choices=[('FORNECEDORES', 'Fornecedores / Insumos'), ('TAXA_PLATAFORMA', 'Taxa de Plataforma (iFood / UaiRango)'), ('TAXA_MAQUININHA', 'Taxa de Maquininha'), ('ENTREGA', 'Entregadores / Motoboy'), ('ENERGIA', 'Energia Elétrica (luz)'), ('AGUA_LUZ', 'Água / Esgoto'), ('INTERNET', 'Internet / Telefone'), ('IMPOSTOS', 'Impostos / Tributos (MEI / DAS)'), ('CONTADOR', 'Contador / Assessoria'), ('MANUTENCAO', 'Manutenção e Equipamentos'), ('VEICULO', 'Veículo / Moto (combustível, manutenção)'), ('GAS', 'Botijão de Gás'), ('MARKETING', 'Influencers / Marketing'), ('EMPRESTIMO', 'Empréstimos / Financiamentos'), ('LIMPEZA', 'Materiais de Limpeza'), ('FUNCIONARIOS', 'Funcionários / Pró-labore'), ('APLICATIVO', 'Aplicativo de Vendas Próprio'), ('RETIRADA_SOCIOS', 'Retirada dos Sócios'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria'),
        ),
    ]
