# Generated by Django 5.0.14 on 2026-09-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_despesa_credor_despesarecorrente_credor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='grupo_parcelas',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Grupo de parcelamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcela_num',
            field=models.PositiveIntegerField(default=1, verbose_name='Nº da parcela'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcela_total',
            field=models.PositiveIntegerField(default=1, verbose_name='Total de parcelas'),
        ),
    ]
