# Generated by Django 5.0.14 on 2026-09-03 18:14
import datetime

from django.db import migrations, models


def preencher_primeiro_vencimento(apps, schema_editor):
    """Recorrentes antigos só tinham 'dia do mês'. Converte para uma data cheia:
    o próximo vencimento a partir de hoje, no dia informado."""
    DespesaRecorrente = apps.get_model('relatorios', 'DespesaRecorrente')
    hoje = datetime.date.today()
    for r in DespesaRecorrente.objects.all():
        if r.primeiro_vencimento:
            continue
        dia = r.dia_vencimento or 1
        ano, mes = hoje.year, hoje.month
        # tenta este mês; se o dia já passou, vai para o mês seguinte
        import calendar
        d = min(dia, calendar.monthrange(ano, mes)[1])
        alvo = datetime.date(ano, mes, d)
        if alvo < hoje:
            mes += 1
            if mes > 12:
                mes = 1
                ano += 1
            d = min(dia, calendar.monthrange(ano, mes)[1])
            alvo = datetime.date(ano, mes, d)
        r.primeiro_vencimento = alvo
        r.frequencia = r.frequencia or 'MENSAL'
        r.save(update_fields=['primeiro_vencimento', 'frequencia'])


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0008_despesa_grupo_parcelas_despesa_parcela_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesarecorrente',
            options={'verbose_name': 'Despesa Recorrente', 'verbose_name_plural': 'Despesas Recorrentes'},
        ),
        migrations.AddField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('AVISTA', 'À vista (dinheiro / pix / débito)'), ('CARTAO', 'Cartão de crédito'), ('BOLETO', 'Boleto'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='despesarecorrente',
            name='frequencia',
            field=models.CharField(choices=[('SEMANAL', 'Semanal (toda semana)'), ('QUINZENAL', 'Quinzenal (a cada 15 dias)'), ('MENSAL', 'Mensal (todo mês)'), ('BIMESTRAL', 'Bimestral (a cada 2 meses)'), ('TRIMESTRAL', 'Trimestral (a cada 3 meses)'), ('SEMESTRAL', 'Semestral (a cada 6 meses)'), ('ANUAL', 'Anual (uma vez por ano)')], default='MENSAL', max_length=12, verbose_name='Frequência'),
        ),
        migrations.AddField(
            model_name='despesarecorrente',
            name='primeiro_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Primeiro Vencimento'),
        ),
        migrations.AlterField(
            model_name='despesarecorrente',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia Padrão de Vencimento'),
        ),
        migrations.RunPython(preencher_primeiro_vencimento, migrations.RunPython.noop),
    ]
