# Generated by Django 5.0.14 on 2026-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0009_alter_despesarecorrente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='grupo_compra',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Grupo da compra'),
        ),
    ]
