# Generated by Django 5.0.14 on 2026-09-01 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('usuario_nome', models.CharField(blank=True, default='', max_length=150, verbose_name='Usuário (texto)')),
                ('acao', models.CharField(choices=[('CRIOU', 'Criou'), ('ALTEROU', 'Alterou'), ('EXCLUIU', 'Excluiu')], max_length=10, verbose_name='Ação')),
                ('modelo', models.CharField(max_length=60, verbose_name='Tipo de registro')),
                ('objeto_id', models.CharField(blank=True, default='', max_length=40, verbose_name='ID do registro')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='O que mudou')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-quando'],
            },
        ),
    ]
