# Generated by Django 5.0.14 on 2026-07-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Insumo')),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (l)'), ('ml', 'Mililitro (ml)'), ('un', 'Unidade (un)')], default='g', max_length=5, verbose_name='Unidade de Medida')),
                ('custo_unitario', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Custo Unitário (R$)')),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor')),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Mínimo')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque Atual')),
                ('categoria', models.CharField(choices=[('PROTEINA', 'Proteínas'), ('PAO', 'Pães'), ('MOLHO', 'Molhos'), ('VEGETAL', 'Vegetais / Saladas'), ('QUEIJO', 'Queijos'), ('EMBALAGEM', 'Embalagens'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ingrediente / Insumo',
                'verbose_name_plural': 'Ingredientes / Insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PrecoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço no Canal (R$)')),
            ],
            options={
                'verbose_name': 'Preço por Canal',
                'verbose_name_plural': 'Preços por Canal',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('categoria', models.CharField(choices=[('BURGER', 'Hambúrgueres (Campeões)'), ('BEBIDA', 'Bebidas'), ('ACOMPANHAMENTO', 'Acompanhamentos'), ('COMBO', 'Combos Hextech')], default='BURGER', max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Lanche')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto do Lanche')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo / Em Linha')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Utilizada')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.ingrediente', verbose_name='Ingrediente / Insumo')),
            ],
            options={
                'verbose_name': 'Item de Ficha Técnica',
                'verbose_name_plural': 'Itens de Ficha Técnica',
            },
        ),
    ]
