# Generated by Django 5.0.14 on 2026-07-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precocanal',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_produtos', to='vendas.canalvenda', verbose_name='Canal de Venda'),
        ),
        migrations.AddField(
            model_name='precocanal',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_canais', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='fichatecnicaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AlterUniqueTogether(
            name='precocanal',
            unique_together={('produto', 'canal')},
        ),
        migrations.AlterUniqueTogether(
            name='fichatecnicaitem',
            unique_together={('produto', 'ingrediente')},
        ),
    ]
