# Generated by Django 5.0.14 on 2026-07-18 21:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Custo Unitário (R$)'),
        ),
    ]
