# Generated by Django 5.0.14 on 2026-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_ingrediente_custo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='unidade_compra',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (l)'), ('ml', 'Mililitro (ml)'), ('un', 'Unidade (un)')], default='g', max_length=5, verbose_name='Unidade de Compra (Entrada)'),
        ),
    ]
