# Generated by Django 5.0.14 on 2026-07-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_ingrediente_unidade_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('BURGER', 'Hambúrgueres (Campeões)'), ('BEBIDA', 'Bebidas'), ('ACOMPANHAMENTO', 'Acompanhamentos e Fritas'), ('COMBO', 'Combos Hextech'), ('ENTRADA', 'Entradas e Porções'), ('CROISSANT', 'Croissants'), ('SOBREMESA', 'Sobremesas e Mimos')], default='BURGER', max_length=20, verbose_name='Categoria'),
        ),
    ]
