# Generated by Django 5.0.14 on 2026-09-01 23:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fichatecnicaitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fichatecnicaitem',
            name='produto_componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usado_em_combos', to='produtos.produto', verbose_name='Produto componente (combo)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_aquisicao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Só para itens de revenda comprados prontos (refrigerante, água, chocolate). Deixe 0 para produtos feitos por ficha técnica.', max_digits=10, verbose_name='Custo de aquisição (revenda)'),
        ),
        migrations.AlterField(
            model_name='fichatecnicaitem',
            name='ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.ingrediente', verbose_name='Ingrediente / Insumo'),
        ),
        migrations.AddConstraint(
            model_name='fichatecnicaitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ingrediente__isnull', False), ('produto_componente__isnull', True)), models.Q(('ingrediente__isnull', True), ('produto_componente__isnull', False)), _connector='OR'), name='ficha_item_ingrediente_xor_produto'),
        ),
    ]
