# Generated by Django 5.0.14 on 2026-07-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Canal')),
                ('taxa_comissao', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Taxa de Comissão (%)')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Fixa por Pedido (R$)')),
                ('dias_repasse', models.IntegerField(default=1, verbose_name='Dias para Repasse')),
            ],
            options={
                'verbose_name': 'Canal de Venda',
                'verbose_name_plural': 'Canais de Venda',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Cliente')),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PREPARO', 'Em Preparo'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='RECEBIDO', max_length=20, verbose_name='Status do Pedido')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Bruto (R$)')),
                ('taxas_canal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxas do Canal (R$)')),
                ('custo_ingredientes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo de Produção (R$)')),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lucro Líquido Real (R$)')),
                ('estoque_baixado', models.BooleanField(default=False, verbose_name='Baixa de Estoque Realizada')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='vendas.canalvenda', verbose_name='Canal de Venda')),
            ],
            options={
                'verbose_name': 'Pedido / Venda',
                'verbose_name_plural': 'Pedidos / Vendas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedido',
            },
        ),
    ]
