# Generated by Django 5.0.14 on 2026-07-19 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Concedido (R$)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('ONLINE', 'Pagamento Online (APP)'), ('PIX_ENTREGA', 'Pix na Entrega (Maquininha)'), ('DINHEIRO_ENTREGA', 'Dinheiro na Entrega'), ('CARTAO_ENTREGA', 'Cartão na Entrega (Maquininha)')], default='ONLINE', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.CreateModel(
            name='TaxaFormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('ONLINE', 'Pagamento Online (APP)'), ('PIX_ENTREGA', 'Pix na Entrega (Maquininha)'), ('DINHEIRO_ENTREGA', 'Dinheiro na Entrega'), ('CARTAO_ENTREGA', 'Cartão na Entrega (Maquininha)')], max_length=20, verbose_name='Forma de Pagamento')),
                ('taxa_comissao', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Taxa (%)')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa Fixa (R$)')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas_pagamento', to='vendas.canalvenda', verbose_name='Canal de Venda')),
            ],
            options={
                'verbose_name': 'Taxa por Forma de Pagamento',
                'verbose_name_plural': 'Taxas por Forma de Pagamento',
                'unique_together': {('canal', 'forma_pagamento')},
            },
        ),
    ]
