# Generated by Django 5.2.13 on 2026-08-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_pedido_desconto_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoDiarioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Fechamento')),
                ('quantidade_entregas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Entregas')),
            ],
            options={
                'verbose_name': 'Informação do Fechamento Diário',
                'verbose_name_plural': 'Informações dos Fechamentos Diários',
            },
        ),
    ]
