# Generated by Django 5.2.13 on 2026-08-09 23:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_fechamentodiarioinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentodiarioinfo',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5, verbose_name='Taxa de Entrega (R$)'),
        ),
    ]
