# Generated by Django 5.2.13 on 2026-08-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_fechamentodiarioinfo_taxa_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Pagamento Online (APP)'), ('PIX_ENTREGA', 'Pix na Entrega (Maquininha)'), ('DINHEIRO_ENTREGA', 'Dinheiro na Entrega'), ('CARTAO_ENTREGA', 'Cartão na Entrega (Maquininha)')], default='ONLINE', max_length=20, null=True, verbose_name='Forma de Pagamento (LEGADO)'),
        ),
        migrations.AlterField(
            model_name='taxaformapagamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Pagamento Online (APP)'), ('PIX_ENTREGA', 'Pix na Entrega (Maquininha)'), ('DINHEIRO_ENTREGA', 'Dinheiro na Entrega'), ('CARTAO_ENTREGA', 'Cartão na Entrega (Maquininha)')], max_length=20, null=True, verbose_name='Forma de Pagamento (LEGADO)'),
        ),
        migrations.AlterUniqueTogether(
            name='taxaformapagamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento', verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='taxaformapagamento',
            name='forma_pagamento_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.formapagamento', verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterUniqueTogether(
            name='taxaformapagamento',
            unique_together={('canal', 'forma_pagamento_fk')},
        ),
    ]
