# Generated by Django 5.2.13 on 2026-08-10 00:06

from django.db import migrations

def migrate_formas_pagamento(apps, schema_editor):
    FormaPagamento = apps.get_model('vendas', 'FormaPagamento')
    Pedido = apps.get_model('vendas', 'Pedido')
    TaxaFormaPagamento = apps.get_model('vendas', 'TaxaFormaPagamento')

    # Mapping based on old choices
    mapping = {
        'ONLINE': 'Pagamento Online (APP)',
        'PIX_ENTREGA': 'Pix na Entrega (Maquininha)',
        'DINHEIRO_ENTREGA': 'Dinheiro na Entrega',
        'CARTAO_ENTREGA': 'Cartão na Entrega (Maquininha)',
    }

    # Create FormaPagamento objects for existing mappings
    fk_map = {}
    for code, name in mapping.items():
        fp, created = FormaPagamento.objects.get_or_create(nome=name)
        fk_map[code] = fp

    # Update Pedido
    for pedido in Pedido.objects.all():
        if pedido.forma_pagamento and pedido.forma_pagamento in fk_map:
            pedido.forma_pagamento_fk = fk_map[pedido.forma_pagamento]
            pedido.save()

    # Update TaxaFormaPagamento
    for taxa in TaxaFormaPagamento.objects.all():
        if taxa.forma_pagamento and taxa.forma_pagamento in fk_map:
            taxa.forma_pagamento_fk = fk_map[taxa.forma_pagamento]
            taxa.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_formapagamento_alter_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_formas_pagamento),
    ]
