# Generated by Django 5.2.13 on 2026-08-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_migrate_formas_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='taxaformapagamento',
            name='forma_pagamento',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='forma_pagamento_fk',
            new_name='forma_pagamento',
        ),
        migrations.RenameField(
            model_name='taxaformapagamento',
            old_name='forma_pagamento_fk',
            new_name='forma_pagamento',
        ),
        migrations.AlterUniqueTogether(
            name='taxaformapagamento',
            unique_together={('canal', 'forma_pagamento')},
        ),
    ]
