# Generated by Django 5.2.13 on 2026-08-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_remove_pedido_forma_pagamento_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxas_pagamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxas de Pagamento/Cartão (R$)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxas_canal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxas do App/Canal (R$)'),
        ),
        migrations.AlterField(
            model_name='taxaformapagamento',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.formapagamento', verbose_name='Forma de Pagamento'),
        ),
    ]
