# Generated by Django 5.0.14 on 2026-09-01 20:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_pedido_taxas_pagamento_alter_pedido_taxas_canal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_maquininha', models.DecimalField(decimal_places=4, default=Decimal('0.0350'), help_text='Ex: 0.035 para 3,5%. Aplicada quando o cliente paga no cartão/pix da maquininha do Igor.', max_digits=6, verbose_name='Taxa da maquininha na entrega (%)')),
                ('taxa_online_plataforma', models.DecimalField(decimal_places=4, default=Decimal('0.0320'), help_text='Ex: 0.032 para 3,2%. Somado à comissão do canal quando o cliente paga dentro do app da plataforma.', max_digits=6, verbose_name='Acréscimo de pagamento on-line no app (%)')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Valor fixo cobrado do cliente e repassado ao entregador por entrega.', max_digits=6, verbose_name='Valor da entrega (R$)')),
                ('caixa_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinheiro que já existia no caixa no dia em que o sistema começou a ser usado.', max_digits=12, verbose_name='Saldo de caixa inicial (R$)')),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configuração Financeira',
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome do Entregador')),
                ('eh_socio', models.BooleanField(default=False, help_text='Se marcado, as entregas feitas por esta pessoa NÃO geram custo de motoboy — o valor fica na empresa.', verbose_name='É sócio (Igor / esposa)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='modo_pagamento',
            field=models.CharField(choices=[('ONLINE', 'Pago no app da plataforma'), ('DINHEIRO', 'Dinheiro na entrega'), ('MAQUININHA', 'Maquininha na entrega')], default='ONLINE', max_length=12, verbose_name='Modo de Pagamento'),
        ),
        migrations.CreateModel(
            name='EntregaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Entregas')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='vendas.entregador', verbose_name='Entregador')),
            ],
            options={
                'verbose_name': 'Entrega do Dia',
                'verbose_name_plural': 'Entregas do Dia',
                'ordering': ['-data', 'entregador__nome'],
                'unique_together': {('data', 'entregador')},
            },
        ),
    ]
