# Generated by Django 5.0.14 on 2026-09-01 21:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_configuracaofinanceira_entregador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='taxa_online_plataforma',
        ),
        migrations.AddField(
            model_name='canalvenda',
            name='taxa_online',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cobrada quando o cliente paga dentro do app. iFood 15,2%, UaiRango 11,5%, app próprio 0%.', max_digits=5, verbose_name='Taxa total no pagamento on-line (%)'),
        ),
        migrations.AlterField(
            model_name='canalvenda',
            name='taxa_comissao',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cobrada quando o cliente paga na entrega. iFood 12%, UaiRango 8%, app próprio 0%.', max_digits=5, verbose_name='Comissão base (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='taxa_maquininha',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0350'), help_text='Ex: 0.035 para 3,5%. Aplicada quando o cliente paga no cartão/pix da maquininha do Igor na entrega.', max_digits=6, verbose_name='Taxa da maquininha na entrega (%)'),
        ),
    ]
