# Generated by Django 5.0.14 on 2026-09-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_ajusta_taxas_canais'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='ultima_geracao_recorrentes',
            field=models.DateField(blank=True, help_text='Controle interno: as faturas dos moldes fixos são geradas no máximo 1x por dia.', null=True, verbose_name='Última geração de contas recorrentes'),
        ),
    ]
