# Generated by Django 5.0.14 on 2026-10-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_configuracaofinanceira_ultima_geracao_recorrentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentodiarioinfo',
            name='desconto_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto do dia (R$)'),
        ),
    ]
